@startuml cinema

class Filme {
    - id int
    - titulo string
    - ano int
    - duracao int
    - descricao string
    - faixa_etaria int
    - diretor string
    - avaliacao_geral string
    - categoria Categoria
    - genero Genero
    + cadastrarFilme(titulo, ano, duracao, descricao, faixa_etaria, diretor, avaliacao_geral, categoria, genero)
    + consultarFilme(id)
    + editarFilme(id)
    + excluirFilme(id)
    + listarFilmes()
}

class Pessoa {
    - id int
    - nome string
    - sobrenome string
    # cpf int
    - idade int
    - dataNascimento date
    + cadastrarPessoa(nome, sobrenome, cpf, idade, dataNascimento)
    + consultarPessoa(cpf)
    + editarPessoa(cpf)
    + excluirPessoa(id)
}

class Categoria {
    - id int
    - titulo string
    - descricao string
    + cadastrarCategoria(titulo, descricao)
    + consultarCategoria(id)
    + editarCategoria(id)
    + excluirCategoria(id)
    + listarCategorias()
}

class Genero {
    - id int
    - nome string
    - descricao string
    + cadastrarGenero(nome, descricao)
    + consultarGenero(id)
    + editarGenero(id)
    + excluirGenero(id)
    + listarGeneros()
}

class Ingresso {
    - id int
    - assento Sala
    - sessao Sessao
    - pessoa Pessoa
    + cadastrarIngresso (nome_comprador, idade_comprador, documento_comprador, assento, sessao, pessoa)
    + consultarDadosComprador(pessoa.id)
    + consultarIngresso(id)
    + excluirIngresso(id)    
    + buscarSessao(sessao.id)
}

class Sala {
    - id int
    - numero_sala int
    - assentos int
    - tipo_sala string
    + cadastrarSala(numero_sala, assentos, tipo_sala)
    + consultarSala(id)
    + editarSala(id)
    + excluirSala(id)
    + listarSalas()
}

class Sessao {
    - id int
    - horario date
    - filme Filme
    - sala Sala
    + cadastrarSessao(horario, filme, sala)
    + consultarSessao(id)
    + editarSessao(id)
    + excluirSessao(id)
    + listarSessoes()
}

Filme *-- Categoria
Filme *-- Genero

Sala --* Sessao

Sessao *-- Filme

Pessoa --* Ingresso

Ingresso *-- Sala

@enduml